apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: artist-api
  description: Retrieve artist details
spec:
  type: openapi
  lifecycle: production
  owner: artist-relations-team
  system: artist-engagement-portal
  definition: 
    $text: https://github.com/VictorianGovernment/api-design-standards/blob/master/api-example-swagger-v1.4.json
