apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: default
  namespace: default
spec:
  type: team
  profile:
    displayName: Default Team
    description: Zespół domyślny
  children: []  # Dodaj to pole, aby spełnić wymagania

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
metadata:
  name: my-component
  namespace: default
  annotations:
    notifications.backstage.io/recipients: group:default/default
spec:
  type: service
  lifecycle: production
  owner: group:default/default
