apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-component
  namespace: default
  annotations:
    notifications.backstage.io/recipients: group:default/default
spec:
  type: service
  lifecycle: production
  owner: group:default/default
