name: Test Workflow

on:
  push:
    branches:
      - main

jobs:
  echo-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Message
        run: echo "Hello, this is a test message for GitHub Actions!"
